insert into test.relationship (id,
                          accepted_date,
                          end_date,
                          created_date,
                          status_enum,
                          submitted_date,
                          archived_date,
                          archived_flag,
                          reminder_flag)
values
  (1,
   PARSEDATETIME('2018-06-27 12:04:54', 'yyyy-MM-dd HH:mm:ss'),
   NULL,
   PARSEDATETIME('2018-06-23 09:04:54', 'yyyy-MM-dd HH:mm:ss'),
   'ACTIVE',
   PARSEDATETIME('2018-06-23 09:32:01', 'yyyy-MM-dd HH:mm:ss'),
   NULL,
   0,
   0),
  (1,
   NULL,
   NULL,
   PARSEDATETIME('2018-06-23 09:04:54', 'yyyy-MM-dd HH:mm:ss'),
   'PENDING',
   PARSEDATETIME('2018-06-23 09:32:01', 'yyyy-MM-dd HH:mm:ss'),
   NULL,
   0,
   0);